### ISSUE TITLE
How different languages work?

### ISSUE THREAD

**Issue by geosaaga** [fmidev/smartmet-alert-client#2]
Could README include instructions how different languages work? I seem to always get finnish version even if try to build for different language using **.env** file with

`
VUE_APP_I18N_LOCALE=en
`

Or is there some method to change language?

**Comment by masapu** [comment]
Thanks for the suggestion. Fixed in the version 3.0.36: The default language is now defined correctly in the .env file. Also, the README contains instructions for language usage.

**Comment by geosaaga** [comment]
Thank you, I tested the language attribute and it works as expected.
